service: webpack-test-tester

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  webpackIncludeModules:
      packagePath: '../../package.json'
  webpack: ../../webpack.config.js

plugins:
  - serverless-webpack

package:
  include:
    - node_modules/**
  exclude:
    - config.json

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: airdev01
  region: us-east-1
  memorySize: 128

functions:

  post:
    handler: index.post
    events:
      - http:
          path: tester/post
          method: post
          cors: true
